apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ parameters.name }}
  description: ${{ parameters.description }}
  annotations:
    github.com/project-slug: ${{ parameters.owner }}/hello-world
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: ${{ parameters.owner }}
